spring.application.name=housekeeping-service
server.port=8082
spring.datasource.url=jdbc:postgresql://hotelos-db:5432/housekeeping_db
spring.datasource.username=hudoyor
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=rabbitmq


# Swagger UI path (Lokalda tekshirish uchun: http://localhost:PORT/swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html
# API hujjatlarining JSON formati manzili
# Ichki servis springdoc'ga o'zining asosiy prefiksini tushuntiradi
springdoc.api-docs.path=/api/housekeeping/v3/api-docs