spring.application.name=reception-service
server.port=8081
# Konteyner ichidan ulanish uchun (PgAdmin bilan adashmaydi)
spring.datasource.url=jdbc:postgresql://hotelos-db:5432/reception_db
spring.datasource.username=hudoyor
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=rabbitmq
spring.data.redis.host=redis

# Swagger UI path (Lokalda tekshirish uchun: http://localhost:PORT/swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html
# API hujjatlarining JSON formati manzili
springdoc.api-docs.path=/api/reception/v3/api-docs