spring.application.name=room-service
server.port=9094
spring.datasource.url=jdbc:postgresql://hotelos-db:5432/room_db
spring.datasource.username=hudoyor
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=rabbitmq
