spring.application.name=maintenance-service
server.port=8085
spring.datasource.url=jdbc:postgresql://hotelos-db:5432/maintenance_db
spring.datasource.username=hudoyor
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=rabbitmq

